name:  Housekeeping - Issues and PRs management
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - or:
        - activitySenderHasAssociation:
            association: FirstTimer
        - activitySenderHasAssociation:
            association: FirstTimeContributor
      then:
      - addReply:
          reply: 'Hi friend! Thanks you for opening this Pull Request. Someone will review it soon. Thank you for committing to making the Azure Arc Jumpstart better.'
      description:
onFailure: 
onSuccess: 
